spring.application.name=social-media-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/social_media
spring.datasource.username=social_media_user
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update